/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyMetadata } from "../../internal/utils";
import { AxiosResponse } from "axios";
import { classToPlain, Exclude, Expose } from "class-transformer";

/**
 * HTTP status code.
 */
export enum CancelSyncRunStatus {
    FourHundredAndFour = 404,
}

/**
 * Resource not found.
 */
export class CancelSyncRunResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    /**
     * HTTP status code.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: CancelSyncRunStatus;

    constructor(err?: CancelSyncRunResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "CancelSyncRunResponseBody";
        Object.setPrototypeOf(this, CancelSyncRunResponseBody.prototype);
    }
}
