/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import * as components from "../../models/components";
import { AxiosResponse } from "axios";

export class FetchDestinationConnectLinkRequest extends SpeakeasyBase {
    /**
     * ID of the connect link
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=connect_link_id" })
    connectLinkId: number;
}

export class FetchDestinationConnectLinkResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Successfully retrieved destination connect link details.
     */
    @SpeakeasyMetadata()
    destinationsConnectFetch?: components.DestinationsConnectFetch;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
