/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import * as components from "../../models/components";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class FetchConnectorRequest extends SpeakeasyBase {
    /**
     * Name of the connector to retrieve
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=service_name" })
    serviceName: string;
}

/**
 * The outcome of the fetch request
 */
export enum Status {
    Success = "success",
}

/**
 * Successfully retrieved the connector
 */
export class FetchConnectorResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => components.Connector)
    data: components.Connector;

    /**
     * The outcome of the fetch request
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: Status;
}

export class FetchConnectorResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Successfully retrieved the connector
     */
    @SpeakeasyMetadata()
    object?: FetchConnectorResponseBody;
}
