/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class GetSourcesSourceIdTablesTableIdRefreshColumnsStatusRequest extends SpeakeasyBase {
    /**
     * An `id` provided by the `refresh_columns` endpoint, used to check whether the refresh columns job has finished.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=refresh_key" })
    refreshKey: number;

    /**
     * ID of the source
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=source_id" })
    sourceId: number;

    /**
     * ID of the table
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=table_id" })
    tableId: number;
}

/**
 * Status of the job
 */
export enum GetSourcesSourceIdTablesTableIdRefreshColumnsStatusStatus {
    Completed = "completed",
    Processing = "processing",
}

/**
 * Successfully checked the status of the job.
 */
export class GetSourcesSourceIdTablesTableIdRefreshColumnsStatusResponseBody extends SpeakeasyBase {
    /**
     * Status of the job
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: GetSourcesSourceIdTablesTableIdRefreshColumnsStatusStatus;
}

export class GetSourcesSourceIdTablesTableIdRefreshColumnsStatusResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Successfully checked the status of the job.
     */
    @SpeakeasyMetadata()
    object?: GetSourcesSourceIdTablesTableIdRefreshColumnsStatusResponseBody;
}
