/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class PostSourcesSourceIdModelsModelIdRefreshColumnsRequest extends SpeakeasyBase {
    /**
     * ID of the model
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=model_id" })
    modelId: number;

    /**
     * ID of the source
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=source_id" })
    sourceId: number;
}

/**
 * Successfully enqueued the column refresh job.
 */
export class PostSourcesSourceIdModelsModelIdRefreshColumnsResponseBody extends SpeakeasyBase {
    /**
     * They key that can be used to check the status of the refresh job.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "refresh_key" })
    refreshKey?: number;
}

export class PostSourcesSourceIdModelsModelIdRefreshColumnsResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Successfully enqueued the column refresh job.
     */
    @SpeakeasyMetadata()
    object?: PostSourcesSourceIdModelsModelIdRefreshColumnsResponseBody;
}
