/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import * as components from "../../models/components";
import { AxiosResponse } from "axios";

export class UpdateSegmentRequest extends SpeakeasyBase {
    /**
     * ID of the segment
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=segment_id" })
    segmentId: number;

    /**
     * ID of the source
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=source_id" })
    sourceId: number;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    configurableSegmentAttributes?: components.ConfigurableSegmentAttributes;
}

export class UpdateSegmentResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Successfully updated the Segment
     */
    @SpeakeasyMetadata()
    segmentsUpdate?: components.SegmentsUpdate;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
