/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { ModelsCheckRefresh } from "./modelscheckrefresh";
import { AxiosResponse } from "axios";

export class CheckModelsColumnRefreshRequest extends SpeakeasyBase {
    /**
     * ID of the model
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=model_id" })
    modelId: number;

    /**
     * An `id` provided by the `refresh_columns` endpoint, used to check whether the refresh columns job has finished.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=refresh_key" })
    refreshKey: number;

    /**
     * ID of the source
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=source_id" })
    sourceId: number;
}

export class CheckModelsColumnRefreshResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Successfully checked the status of the job.
     */
    @SpeakeasyMetadata()
    modelsCheckRefresh?: ModelsCheckRefresh;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;
}
