/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { Expose } from "class-transformer";

export class Column extends SpeakeasyBase {
    /**
     * The name of the column.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The data type of the column.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;
}
