/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The credentials to be used for this service connection. Refer to the connector API for details for your connection type.
 */
export class Credentials extends SpeakeasyBase {}

/**
 * Contains the information for the connection.
 */
export class ServiceConnection extends SpeakeasyBase {
    /**
     * The credentials to be used for this service connection. Refer to the connector API for details for your connection type.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "credentials" })
    @Type(() => Credentials)
    credentials?: Credentials;

    /**
     * The name of this destination.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class ConfigurableDestinationAttributes extends SpeakeasyBase {
    /**
     * Contains the information for the connection.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "service_connection" })
    @Type(() => ServiceConnection)
    serviceConnection?: ServiceConnection;
}
