/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Contains the information for the connection.
 */
export class Connection extends SpeakeasyBase {
    /**
     * Credentials that should be associated with this source (e.g. hostname, port)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "credentials" })
    credentials?: Record<string, any>;

    /**
     * An optional label that can be assigned to the source for better categorization or identification.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "label" })
    label?: string;
}

export class ConfigurableSourceAttributes extends SpeakeasyBase {
    /**
     * Contains the information for the connection.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection?: Connection;
}
