/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { DestinationConnectLink } from "./destinationconnectlink";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * Outcome of the operation.
 */
export enum CreateDestinationConnectLinkStatus {
    Success = "success",
    Updated = "updated",
    Created = "created",
    NotFound = "not_found",
    Error = "error",
}

/**
 * Destination connect link created successfully
 */
export class CreateDestinationConnectLinkResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => DestinationConnectLink)
    data?: DestinationConnectLink;

    /**
     * Outcome of the operation.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: CreateDestinationConnectLinkStatus;
}

export class CreateDestinationConnectLinkResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Destination connect link created successfully
     */
    @SpeakeasyMetadata()
    object?: CreateDestinationConnectLinkResponseBody;
}
