/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { SuccessfulDeleteResult } from "./successfuldeleteresult";
import { AxiosResponse } from "axios";
import { classToPlain, Exclude, Expose } from "class-transformer";

export class DeleteSyncRequest extends SpeakeasyBase {
    /**
     * ID of the sync
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=sync_id" })
    syncId: number;
}

/**
 * HTTP status code.
 */
export enum DeleteSyncStatus {
    FourHundredAndFour = 404,
}

/**
 * Resource not found.
 */
export class DeleteSyncResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    /**
     * HTTP status code.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: DeleteSyncStatus;

    constructor(err?: DeleteSyncResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "DeleteSyncResponseBody";
        Object.setPrototypeOf(this, DeleteSyncResponseBody.prototype);
    }
}

export class DeleteSyncResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Successfully deleted the sync.
     */
    @SpeakeasyMetadata()
    successfulDeleteResult?: SuccessfulDeleteResult;
}
