/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { Expose, Transform } from "class-transformer";

export class DestinationConnectLink extends SpeakeasyBase {
    /**
     * The ID of the destination, if any, associated with the data.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "destination_id" })
    destinationId?: number;

    /**
     * The date and time when the Connect Link will expire.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "expiration" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    expiration: Date;

    /**
     * The unique ID associated with the Connect Link.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    /**
     * The redirect URI, if any, associated with the Connect Link. The URL that you'd like the end-user to be redirected to after authorizing the destination. We do not forward the OAuth code or token to this url. The redirect URI can be configured globally under your organization settings in the Census UI or on dynamically via the API when creating a Connect Link.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "redirect_uri" })
    redirectUri?: string;

    /**
     * A boolean value indicating whether the Connect Link has been revoked or not.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "revoked" })
    revoked: boolean;

    /**
     * The type of destination connection to be managed by this link. The list of valid types can be fetched from `/destination_connect_links/types`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;

    /**
     * The authorization url that you will provide to end-users that begins the Census-hosted flow to authorize a destination into your workspace.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "uri" })
    uri: string;
}
