/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { DestinationConnectLink } from "./destinationconnectlink";
import { Expose, Type } from "class-transformer";

export class DestinationsConnectRevoke extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => DestinationConnectLink)
    data: DestinationConnectLink;

    /**
     * The outcome of the revoke request
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: any;
}
