/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class GetDestinationsDestinationIdRefreshObjectsStatusRequest extends SpeakeasyBase {
    /**
     * ID of the destination with an active refresh job
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=destination_id" })
    destinationId: number;

    /**
     * An `id` provided by the `refresh_objects` endpoint, used to check whether the refresh objects job has finished.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=refresh_key" })
    refreshKey: number;
}

/**
 * Status of the job.
 */
export enum GetDestinationsDestinationIdRefreshObjectsStatusStatus {
    Completed = "completed",
    Processing = "processing",
}

/**
 * Successfully checked the status of the job.
 */
export class GetDestinationsDestinationIdRefreshObjectsStatusResponseBody extends SpeakeasyBase {
    /**
     * Status of the job.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: GetDestinationsDestinationIdRefreshObjectsStatusStatus;
}

export class GetDestinationsDestinationIdRefreshObjectsStatusResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Successfully checked the status of the job.
     */
    @SpeakeasyMetadata()
    object?: GetDestinationsDestinationIdRefreshObjectsStatusResponseBody;
}
