/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { Order } from "./order";
import { Pagination } from "./pagination";
import { SyncRun } from "./syncrun";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetSyncsSyncIdSyncRunsRequest extends SpeakeasyBase {
    /**
     * The ID of the sync for which to list runs.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=sync_id" })
    syncId: number;

    /**
     * Organizes the results based on their creation time, either ascending or descending.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=order" })
    order?: Order;

    /**
     * Designates which page of results to return. Always starts at 1. If 0 is specified, it defaults to 1.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=page" })
    page?: number;

    /**
     * Determines the number of results on each page. It can't exceed 100.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=per_page" })
    perPage?: number;
}

/**
 * The outcome of the request
 */
export enum GetSyncsSyncIdSyncRunsStatus {
    Success = "success",
}

/**
 * A successfully fetched list of results.
 */
export class GetSyncsSyncIdSyncRunsResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: SyncRun })
    @Expose({ name: "data" })
    @Type(() => SyncRun)
    data: SyncRun[];

    /**
     * An object to help you navigate the list of results.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "pagination" })
    @Type(() => Pagination)
    pagination: Pagination;

    /**
     * The outcome of the request
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: GetSyncsSyncIdSyncRunsStatus;
}

export class GetSyncsSyncIdSyncRunsResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Successfully retrieved the list of sync runs.
     */
    @SpeakeasyMetadata()
    object?: GetSyncsSyncIdSyncRunsResponseBody;
}
