/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { Table } from "./table";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetSourcesSourceIdTablesTableIdRequest extends SpeakeasyBase {
    /**
     * ID of the source
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=source_id" })
    sourceId: number;

    /**
     * ID of the table
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=table_id" })
    tableId: number;
}

/**
 * Outcome of the operation.
 */
export enum GetSourcesSourceIdTablesTableIdStatus {
    Success = "success",
    Updated = "updated",
    Created = "created",
    NotFound = "not_found",
    Error = "error",
}

/**
 * Successfully retrieved the table
 */
export class GetSourcesSourceIdTablesTableIdResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => Table)
    data?: Table;

    /**
     * Outcome of the operation.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: GetSourcesSourceIdTablesTableIdStatus;
}

export class GetSourcesSourceIdTablesTableIdResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Successfully retrieved the table
     */
    @SpeakeasyMetadata()
    object?: GetSourcesSourceIdTablesTableIdResponseBody;
}
