/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { Segment } from "./segment";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetSourcesSourceIdFilterSegmentsSegmentIdRequest extends SpeakeasyBase {
    /**
     * ID of the segment
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=segment_id" })
    segmentId: number;

    /**
     * ID of the source
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=source_id" })
    sourceId: number;
}

/**
 * Outcome of the operation.
 */
export enum GetSourcesSourceIdFilterSegmentsSegmentIdStatus {
    Success = "success",
    Updated = "updated",
    Created = "created",
    NotFound = "not_found",
    Error = "error",
}

/**
 * Successfully retrieved the segment
 */
export class GetSourcesSourceIdFilterSegmentsSegmentIdResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => Segment)
    data?: Segment;

    /**
     * Outcome of the operation.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: GetSourcesSourceIdFilterSegmentsSegmentIdStatus;
}

export class GetSourcesSourceIdFilterSegmentsSegmentIdResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Successfully retrieved the segment
     */
    @SpeakeasyMetadata()
    object?: GetSourcesSourceIdFilterSegmentsSegmentIdResponseBody;
}
