/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { ConfigurableDestinationAttributes } from "./configurabledestinationattributes";
import { Destination } from "./destination";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class PatchDestinationsDestinationIdRequest extends SpeakeasyBase {
    /**
     * ID of the destination to update
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=destination_id" })
    destinationId: number;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    configurableDestinationAttributes?: ConfigurableDestinationAttributes;
}

/**
 * Outcome of the operation.
 */
export enum PatchDestinationsDestinationIdStatus {
    Success = "success",
    Updated = "updated",
    Created = "created",
    NotFound = "not_found",
    Error = "error",
}

/**
 * Successfully updated the destination
 */
export class PatchDestinationsDestinationIdResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => Destination)
    data?: Destination;

    /**
     * Outcome of the operation.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: PatchDestinationsDestinationIdStatus;
}

export class PatchDestinationsDestinationIdResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Successfully updated the destination
     */
    @SpeakeasyMetadata()
    object?: PatchDestinationsDestinationIdResponseBody;
}
