/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { RefreshKey } from "./refreshkey";
import { AxiosResponse } from "axios";

export class PostSourcesSourceIdTablesTableIdRefreshColumnsRequest extends SpeakeasyBase {
    /**
     * ID of the source
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=source_id" })
    sourceId: number;

    /**
     * ID of the table
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=table_id" })
    tableId: number;
}

export class PostSourcesSourceIdTablesTableIdRefreshColumnsResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Successfully enqueued the column refresh job.
     */
    @SpeakeasyMetadata()
    refreshKey?: RefreshKey;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
