/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { DestinationsStartField } from "./destinationsstartfield";
import { AxiosResponse } from "axios";

export class StartFieldRefreshRequest extends SpeakeasyBase {
    /**
     * ID of the destination to update
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=destination_id" })
    destinationId: number;

    /**
     * `full_name` of the destination object
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=object_full_name" })
    objectFullName: number;
}

export class StartFieldRefreshResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Successfully enqueued the fields refresh job.
     */
    @SpeakeasyMetadata()
    destinationsStartField?: DestinationsStartField;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;
}
