/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { Expose, Type } from "class-transformer";

export class SyncTriggerData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "sync_run_id" })
    syncRunId?: number;
}

/**
 * The outcome of the fetch request
 */
export enum SyncTriggerStatus {
    Success = "success",
}

export class SyncTrigger extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => SyncTriggerData)
    data: SyncTriggerData;

    /**
     * The outcome of the fetch request
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: SyncTriggerStatus;
}
