/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { SyncTriggerReason } from "./synctriggerreason";
import { Expose, Transform, Type } from "class-transformer";

/**
 * The current step of the sync run. Available if the sync is running.
 */
export enum CurrentStep {
    CheckingForColumnsToRemoveFromTheSync = "Checking for columns to remove from the sync",
    CheckingForFieldsToCreateInDestination = "Checking for fields to create in destination",
    CheckingSourceAndDestinationConfiguration = "Checking source and destination configuration",
    UnloadingDataFromWarehouse = "Unloading data from warehouse",
    LoadingDataIntoDestinationService = "Loading data into destination service",
    CommittingDataToDestinationService = "Committing data to destination service",
    CommittingSyncToWarehouse = "Committing sync to warehouse",
    RunningSync = "Running sync",
}

/**
 * Status of the sync run. Possible values are:
 *
 * @remarks
 * - `working`: The sync is currently executing.
 * - `completed`: The sync finished successfully.
 * - `failed`: The sync failed during execution.
 * - `skipped`: An earlier instance of the sync is still running, so this run was skipped.
 * - `queued`: The sync run is queued for execution.
 *
 */
export enum SyncRunStatus {
    Working = "working",
    Completed = "completed",
    Failed = "failed",
    Skipped = "skipped",
    Queued = "queued",
}

export class SyncRun extends SpeakeasyBase {
    /**
     * Whether or not this sync run was canceled.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "canceled" })
    canceled?: boolean;

    /**
     * When this sync run was completed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "completed_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    completedAt?: Date;

    /**
     * When this sync run was created.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    createdAt?: Date;

    /**
     * The current step of the sync run. Available if the sync is running.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "current_step" })
    currentStep?: CurrentStep;

    /**
     * The error code, if any.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "error_code" })
    errorCode?: string;

    /**
     * Details about the error, if any.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "error_detail" })
    errorDetail?: string;

    /**
     * The error message, if any.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "full_sync" })
    @Type(() => SyncTriggerReason)
    fullSync?: SyncTriggerReason;

    /**
     * ID of this sync run.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * Number of records rejected by the destination.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "records_failed" })
    recordsFailed?: number;

    /**
     * Number of records skipped by Census because of data quality issues.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "records_invalid" })
    recordsInvalid?: number;

    /**
     * Number of new or updated records retrieved from the source.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "records_processed" })
    recordsProcessed?: number;

    /**
     * Number of records successfully sent to the destination.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "records_updated" })
    recordsUpdated?: number;

    /**
     * When the sync run was scheduled to run.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "scheduled_execution_time" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    scheduledExecutionTime?: Date;

    /**
     * The number of records in the source object at the time of the sync run.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "source_record_count" })
    sourceRecordCount?: number;

    /**
     * Status of the sync run. Possible values are:
     *
     * @remarks
     * - `working`: The sync is currently executing.
     * - `completed`: The sync finished successfully.
     * - `failed`: The sync failed during execution.
     * - `skipped`: An earlier instance of the sync is still running, so this run was skipped.
     * - `queued`: The sync run is queued for execution.
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: SyncRunStatus;

    /**
     * ID of the sync.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sync_id" })
    syncId?: number;

    /**
     * When this sync run was updated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updatedAt?: Date;
}
