/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { Pagination } from "./pagination";
import { Expose, Type } from "class-transformer";

/**
 * The outcome of the request
 */
export enum SyncListStatus {
    Success = "success",
}

/**
 * A successfully fetched list of results.
 */
export class SyncList extends SpeakeasyBase {
    /**
     * The list of results.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    data: any[];

    /**
     * An object to help you navigate the list of results.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "pagination" })
    @Type(() => Pagination)
    pagination: Pagination;

    /**
     * The outcome of the request
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: SyncListStatus;
}
