/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { Column } from "./column";
import { Expose, Type } from "class-transformer";

/**
 * The type of this source object, will always be `table`.
 */
export enum TableType {
    Table = "table",
}

export class Table extends SpeakeasyBase {
    /**
     * A list of columns from this table.
     */
    @SpeakeasyMetadata({ elemType: Column })
    @Expose({ name: "columns" })
    @Type(() => Column)
    columns?: Column[];

    /**
     * The id of this table.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * The catalog associated with this table.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "table_catalog" })
    tableCatalog?: string;

    /**
     * The name of this table.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "table_name" })
    tableName?: string;

    /**
     * The schema associated with this table.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "table_schema" })
    tableSchema?: string;

    /**
     * The type of this source object, will always be `table`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: TableType;
}
