/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { ConfigurableSourceAttributes } from "./configurablesourceattributes";
import { SourcesUpdate } from "./sourcesupdate";
import { AxiosResponse } from "axios";

export class UpdateSourceRequest extends SpeakeasyBase {
    /**
     * ID of the source to update
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=source_id" })
    sourceId: number;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    configurableSourceAttributes?: ConfigurableSourceAttributes;
}

export class UpdateSourceResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Successfully updated the source
     */
    @SpeakeasyMetadata()
    sourcesUpdate?: SourcesUpdate;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
