/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Pagination } from "./pagination";
import { Expose, Type } from "class-transformer";

export class DestinationsConnectListData extends SpeakeasyBase {}

/**
 * The outcome of the request
 */
export enum DestinationsConnectListStatus {
    Success = "success",
}

/**
 * A successfully fetched list of results.
 */
export class DestinationsConnectList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => DestinationsConnectListData)
    data: DestinationsConnectListData;

    /**
     * An object to help you navigate the list of results.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "pagination" })
    @Type(() => Pagination)
    pagination: Pagination;

    /**
     * The outcome of the request
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: DestinationsConnectListStatus;
}
