/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { DestinationObject } from "./destinationobject";
import { Expose, Type } from "class-transformer";

export class Destination extends SpeakeasyBase {
    /**
     * Connection details associated with this destination.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "connection_details" })
    connectionDetails?: Record<string, any>;

    /**
     * The id of this destination.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * The name of this destination.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * A list of objects associated with this destination.
     */
    @SpeakeasyMetadata({ elemType: DestinationObject })
    @Expose({ name: "objects" })
    @Type(() => DestinationObject)
    objects?: DestinationObject[];
}
